### ISSUE TITLE
Error: Cannot read property 'type' of undefined, when generating Typescript for array fields

### ISSUE THREAD

**Issue by tomitrescak** [prismagraphql/prisma-binding#202]
Hi, I am having issues generating Typescript schemas for queries returning arrays. Following works with no issues:

```graphql
type Query {
  notifications(start: Int, end: Int): Notification
}
```

following throws an error below:

```graphql
type Query {
  notifications(start: Int, end: Int): [Notification]!
}
```

Error:

```
TypeError: Cannot read property 'type' of undefined
    at getWhere (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/dist/utils.js:44:9)
    at /Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/utils.ts:41:12
    at Array.map (<anonymous>)
    at getTypesAndWhere (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/utils.ts:38:21)
    at Object.getExistsTypes (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/utils.ts:9:17)
    at PrismaTypescriptGenerator.renderExists (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/PrismaTypescriptGenerator.ts:71:20)
    at PrismaTypescriptGenerator.render (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/PrismaTypescriptGenerator.ts:19:32)
    at /Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/bin.ts:69:34
    at step (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/dist/bin.js:33:23)
    at Object.next (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/dist/bin.js:14:53)
```

**Comment by marktani** [comment]
What are the exact steps you follow?
How can I reproduce this?

**Comment by tomitrescak** [comment]
Hi.

Prisma.yml

```
endpoint: http://localhost:4466
datamodel: 
  - users.graphql
hooks:
  post-deploy:
    - graphql get-schema -p prisma
    - graphql codegen
```

.graphqlconfig

```
projects:
  app:
    schemaPath: "src/data/yoga/schema.graphql"
    includes: ["src/**/*.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:4000"
      codegen:
        - generator: prisma-binding
          language: typescript
          output: 
            binding: src/data/generated/api.ts
  prisma:
    schemaPath: "src/data/generated/prisma.graphql"
    includes: ["src/**/*.graphql"]
    extensions:
      prisma: src/data/prisma/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output: 
            binding: src/data/generated/prisma.ts
```

users.graphql

```graphql
type User {
  id: ID! @unique
  name: String!
  roles: [String!]!
}
```

Now, as for YOGA

schema.graphql

```
#import User from '../generated/prisma.graphql'

type Query {
  users: [User]!
}
```

Now I run `prisma deploy`

```
Running graphql get-schema -p prisma ✔
TypeError: Cannot read property 'type' of undefined
    at getWhere (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/dist/utils.js:44:9)
    at /Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/utils.ts:41:12
    at Array.map (<anonymous>)
    at getTypesAndWhere (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/utils.ts:38:21)
    at Object.getExistsTypes (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/utils.ts:9:17)
    at PrismaTypescriptGenerator.renderExists (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/PrismaTypescriptGenerator.ts:71:20)
    at PrismaTypescriptGenerator.render (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/PrismaTypescriptGenerator.ts:19:32)
    at /Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/src/bin.ts:69:34
    at step (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/dist/bin.js:33:23)
    at Object.next (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-binding/dist/bin.js:14:53)


Running graphql codegen ✖
```

**Comment by marktani** [comment]
Please share the following:

* `prisma version`
* Prisma server version
* `graphql --version`
* Node version
* OS

**Comment by tomitrescak** [comment]
**prisma version**: prisma/1.10.2 (darwin-x64) node-v10.2.1
**Prisma server version**: ??? ... I use the docker image that was built yesterday
**graphql --version**: 2.16.4
Node version: 10.2.1
OS: Mac High Sierra

**Comment by tomitrescak** [comment]
[EDIT] I have just update Prisma to 1.11.1 and the error remains.

**Comment by edorivai** [comment]
Having the exact same problem. My setup:

- prisma version: prisma/1.12.0 (linux-x64) node-v10.5.0
- Prisma server version: prismagraphql/prisma:1.12
- graphql --version: 2.16.4
- Node version: 10.5.0
- OS: Ubuntu 16.04

**Comment by edorivai** [comment]
I think I might understand what's happening here. I was using the `prisma-binding` against my app, as well as against the prisma database. It works against prisma, but fails against my own app. For my own app, I'm now using the `graphql-binding`, you can check https://github.com/graphql-binding/graphql-binding-github for an example.

I'm new to prisma and this was not 100% clear from the docs. I think most people that are just getting started will have the same setup as I do; a prisma service and an "app". Perhaps the codegen docs could more explicitly touch on this case, and outline that the prisma service needs `prisma-binding`, while your app needs the `graphql-binding`.

**Comment by mattferrin** [comment]
@edorivai Your solution appears to work, but takes me back to the initial issue I had using other techniques. I need to support graphql imports.

```
# import TeamConnection from "./generated/prisma.graphql"
```

```
Error: Type "TeamConnection" not found in document.
```

**Comment by mattferrin** [comment]
@edorivai Nevermind. Works perfectly using `graphql-import`. I'm just a little slow this time.

```js
// for typescript types generation only
const fs = require("fs");
const { makeExecutableSchema } = require("graphql-tools");
const { GraphQLSchema } = require("graphql");
const { importSchema } = require("graphql-import");

const typeDefs = importSchema(__dirname + "/schema.graphql");
const schema = makeExecutableSchema({
  typeDefs: typeDefs
});

module.exports = schema;
```

```yml
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
      codegen:
        - generator: graphql-binding
          language: typescript
          input:
            schema: src/schema.js
          output:
            binding: src/generated/app.ts
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
```
