### ISSUE TITLE
Failed graphql codegen after update

### ISSUE THREAD

**Issue by ancashoria** [prismagraphql/prisma-binding#213]
Hey guys, I have updated to prisma-binding: 2.1.1 and followed the upgrading steps from https://www.prisma.io/docs/reference/prisma-bindings/code-generation-cosha9rah3/#upgrading-from-prisma-binding-v1.x

When running `prisma deloy` I get this error at graphql codegen step
```bash
/Users/ancashoria/Workspace/personal/toucan/node_modules/prisma-binding/dist/bin.js:73
    .demandOption(['i', 'l', 'b']).argv;
     ^

TypeError: yargs.usage(...).options(...).demandOption is not a function
    at Object.<anonymous> (/Users/ancashoria/Workspace/personal/toucan/node_modules/prisma-binding/dist/bin.js:73:6)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

.graphqlconfig
```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
```

prisma.yml
```yml
datamodel: datamodel.graphql

secret: ${env:PRISMA_SECRET}

hooks:
  post-deploy:
    - graphql get-schema --project database
    - graphql codegen

endpoint: http://localhost:4466
```

* **prisma -v**: 1.12.0
* **prisma docker image**: prismagraphql/prisma:1.12
* **graphql -v**: 2.16.4
* **node -v**: v9.1.0
* **os**: Mac High Sierra
